<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>nsc</AssemblyName>
    <PublishAot>true</PublishAot>

    <!-- NativeAOT optimization flags -->
    <IlcTrimMetadata>true</IlcTrimMetadata>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    <IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    <IlcOptimizationPreference>speed</IlcOptimizationPreference>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IlcInstructionSet>avx2,aes</IlcInstructionSet>
    <IlcDisableReflection>true</IlcDisableReflection>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetricsSupport>false</MetricsSupport>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <Import Project="..\..\OutputPath.props" />

  <ItemGroup>
    <ProjectReference Include="..\NitroSharp.NsScript\NitroSharp.NsScript.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-rc.2.25502.107"/>
  </ItemGroup>

</Project>
