//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitroSharp.NsScriptNew {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NitroSharp.NsScript.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a member declaration..
        /// </summary>
        internal static string ExpectedMemeberDeclaration {
            get {
                return ResourceManager.GetString("ExpectedMemeberDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only assignment, call, increment and decrement expressions can be used as a statement..
        /// </summary>
        internal static string InvalidExpressionStatement {
            get {
                return ResourceManager.GetString("InvalidExpressionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression term &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidExpressionTerm {
            get {
                return ResourceManager.GetString("InvalidExpressionTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;;&apos;.
        /// </summary>
        internal static string MisplacedSemicolon {
            get {
                return ResourceManager.GetString("MisplacedSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement is not properly terminated..
        /// </summary>
        internal static string MissingStatementTerminator {
            get {
                return ResourceManager.GetString("MissingStatementTerminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stray PXml element..
        /// </summary>
        internal static string StrayPXmlElement {
            get {
                return ResourceManager.GetString("StrayPXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stray token &apos;{0}&apos;..
        /// </summary>
        internal static string StrayToken {
            get {
                return ResourceManager.GetString("StrayToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos;, found &apos;{1}&apos;..
        /// </summary>
        internal static string TokenExpected {
            get {
                return ResourceManager.GetString("TokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is not properly terminated..
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue block identifier is not properly terminated..
        /// </summary>
        internal static string UnterminatedDialogueBlockIdentifier {
            get {
                return ResourceManager.GetString("UnterminatedDialogueBlockIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue block start tag is not properly terminated..
        /// </summary>
        internal static string UnterminatedDialogueBlockStartTag {
            get {
                return ResourceManager.GetString("UnterminatedDialogueBlockStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoted identifier is not properly terminated..
        /// </summary>
        internal static string UnterminatedQuotedIdentifier {
            get {
                return ResourceManager.GetString("UnterminatedQuotedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not properly terminated..
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
    }
}
