<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
<!--    <AssemblyName>libnitrosharp</AssemblyName>-->
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>1701;1702;CA1063;IDE1006;IDE0063;VSTHRD002;VSTHRD003;VSTHRD103;VSTHRD105;VSTHRD200</NoWarn>
    <RootNamespace>NitroSharp</RootNamespace>
  </PropertyGroup>

  <Import Project="..\..\OutputPath.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\third_party\FFmpeg.AutoGen\FFmpeg.AutoGen.csproj" />
    <ProjectReference Include="..\..\third_party\OpenAL-CS\OpenAL-CS.csproj" />
    <ProjectReference Include="..\FreeTypeBindings\FreeTypeBindings.csproj" />
    <ProjectReference Include="..\NitroSharp.NsScript\NitroSharp.NsScript.csproj" />

    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All" />

    <PackageReference Include="ppy.SDL3-CS" Version="2025.1205.0" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.14.15" />
    <PackageReference Include="Sprintf.NET" Version="2.0.0" />

    <PackageReference Include="Veldrid" Version="1.0.0" />
    <PackageReference Include="Veldrid.ImageSharp" Version="1.0.0" />

    <PackageReference Include="Vortice.XAudio2" Version="3.5.0" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.5.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />

    <PackageReference Include="FreeType.Binaries" Version="0.42.0" />
    <PackageReference Include="OpenALSoft.Binaries" Version="0.42.0" />
    <PackageReference Include="FFmpeg.Binaries" Version="0.42.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../fonts/**" LinkBase="Fonts">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NitroSharp.SourceGenerators\NitroSharp.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Graphics/Shaders/**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Runner.cs" />
  </ItemGroup>

  <Target Name="EmbedGeneratedShaderContent" AfterTargets="AssignTargetPaths">
    <ItemGroup>
      <GeneratedShaders Include="$(BaseIntermediateOutputPath)\Shaders.Generated\**" />
      <EmbeddedResource Include="@(GeneratedShaders)">
        <LogicalName>NitroSharp.Graphics.Shaders.%(FileName)%(Extension)</LogicalName>
      </EmbeddedResource>
    </ItemGroup>
  </Target>

</Project>
