namespace NitroSharp.NsScript
{
    public enum BuiltInFunction : byte
    {
        Request,
        SetAlias,
        Delete,
        CreateProcess,
        CreateName,

        Wait,
        WaitKey,

        LoadImage,
        LoadColor,
        CreateColor,
        CreateTexture,
        CreateClipTexture,
        CreateMask,
        CreateWindow,
        CreateChoice,

        CreateText,
        LoadFont,
        LoadText,
        SetFont,
        WaitText,

        CreateCube,
        SetFov,

        CreateMovie,
        WaitPlay,

        Fade,
        Move,
        Zoom,
        Rotate,
        MoveCube,
        BezierMove,
        DrawTransition,
        WaitMove,
        WaitAction,

        Shake,
        SetBlur,
        CreateEffect,
        SetTone,
        SetShade,
        Draw,
        SetVertex,

        CreateSound,
        SetVolume,
        SetLoop,
        SetLoopPoint,

        DurationTime,
        PassageTime,
        RemainTime,
        ImageHorizon,
        ImageVertical,
        Random,
        SoundAmplitude,
        Platform,
        ModuleFileName,
        String,
        Time,
        Integer,
        DateTime,
        CursorPosition,
        Position,

        SetNextFocus,
        MoveCursor,

        LoadFile,
        UnloadFile,
        Save,
        Load,
        ExistSave,
        ClearScore,
        Reset,
        DeleteSaveFile,
        MountSavedata,
        AvailableFile,
        Escape,

        CreateBacklog,
        SetBacklog,
        EnableBacklog,
        ClearBacklog,

        CreateScrollbar,
        SetScrollbar,
        ScrollbarValue,
        SetScrollSpeed,

        SetFrequency,
        SetPan,
        SetStream,
        Exit,

        XBOX360_LockVideo,
        XBOX360_Presence,
        XBOX360_AwardGameIcon,
        XBOX360_Achieved,
        XBOX360_IsAchieved,
        XBOX360_InitUser,
        XBOX360_IsSignin,
        XBOX360_CheckStorage,
        XBOX360_SelectStorage,
        XBOX360_ExistContent,
        XBOX360_StorageSize,
        XBOX360_UserIndex,
        XBOX360_PadTrigger,
        XBOX360_CurrentStorage,

        log,
        assert,
        assert_eq,
        fail,
        fail_msg
    }
}
