<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <WarningsAsErrors>NU1605;CS8625;CS8600;CS8603</WarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <Import Project="..\..\OutputPath.props" />

  <ItemGroup>
    <ProjectReference Include="..\NitroSharp.Common\NitroSharp.Common.csproj" />
    <ProjectReference Include="..\NitroSharp.SourceGenerators\NitroSharp.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" PrivateAssets="All" />
    <PackageReference Include="UTF.Unknown" Version="2.6.0" />
  </ItemGroup>

</Project>
